/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ClientRouteImport } from './routes/client'
import { Route as CollaborationsRouteImport } from './routes/collaborations'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SectorsRouteImport } from './routes/sectors'
import { Route as TeamRouteImport } from './routes/team'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminMatchesRouteImport } from './routes/admin.matches'
import { Route as AdminPartnersRouteImport } from './routes/admin.partners'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminWasteRouteImport } from './routes/admin.waste'
import { Route as ClientIndexRouteImport } from './routes/client.index'
import { Route as ClientMatchesRouteImport } from './routes/client.matches'
import { Route as ClientRecommendationsRouteImport } from './routes/client.recommendations'
import { Route as ClientScorecardRouteImport } from './routes/client.scorecard'
import { Route as ClientWasteRouteImport } from './routes/client.waste'
import { Route as AdminAuditsNewRouteImport } from './routes/admin.audits.new'
import { Route as AdminClientsIndexRouteImport } from './routes/admin.clients.index'
import { Route as AdminClientsClientIdRouteImport } from './routes/admin.clients.$clientId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const CollaborationsRoute = CollaborationsRouteImport.update({
  id: '/collaborations',
  path: '/collaborations',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SectorsRoute = SectorsRouteImport.update({
  id: '/sectors',
  path: '/sectors',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMatchesRoute = AdminMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPartnersRoute = AdminPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWasteRoute = AdminWasteRouteImport.update({
  id: '/waste',
  path: '/waste',
  getParentRoute: () => AdminRoute,
} as any)
const ClientIndexRoute = ClientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientRoute,
} as any)
const ClientMatchesRoute = ClientMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => ClientRoute,
} as any)
const ClientRecommendationsRoute = ClientRecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => ClientRoute,
} as any)
const ClientScorecardRoute = ClientScorecardRouteImport.update({
  id: '/scorecard',
  path: '/scorecard',
  getParentRoute: () => ClientRoute,
} as any)
const ClientWasteRoute = ClientWasteRouteImport.update({
  id: '/waste',
  path: '/waste',
  getParentRoute: () => ClientRoute,
} as any)
const AdminAuditsNewRoute = AdminAuditsNewRouteImport.update({
  id: '/audits/new',
  path: '/audits/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsIndexRoute = AdminClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsClientIdRoute = AdminClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/collaborations': typeof CollaborationsRoute
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/sectors': typeof SectorsRoute
  '/team': typeof TeamRoute
  '/admin/matches': typeof AdminMatchesRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/waste': typeof AdminWasteRoute
  '/client/matches': typeof ClientMatchesRoute
  '/client/recommendations': typeof ClientRecommendationsRoute
  '/client/scorecard': typeof ClientScorecardRoute
  '/client/waste': typeof ClientWasteRoute
  '/admin/': typeof AdminIndexRoute
  '/client/': typeof ClientIndexRoute
  '/admin/audits/new': typeof AdminAuditsNewRoute
  '/admin/clients/$clientId': typeof AdminClientsClientIdRoute
  '/admin/clients/': typeof AdminClientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collaborations': typeof CollaborationsRoute
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/sectors': typeof SectorsRoute
  '/team': typeof TeamRoute
  '/admin/matches': typeof AdminMatchesRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/waste': typeof AdminWasteRoute
  '/client/matches': typeof ClientMatchesRoute
  '/client/recommendations': typeof ClientRecommendationsRoute
  '/client/scorecard': typeof ClientScorecardRoute
  '/client/waste': typeof ClientWasteRoute
  '/admin': typeof AdminIndexRoute
  '/client': typeof ClientIndexRoute
  '/admin/audits/new': typeof AdminAuditsNewRoute
  '/admin/clients/$clientId': typeof AdminClientsClientIdRoute
  '/admin/clients': typeof AdminClientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/collaborations': typeof CollaborationsRoute
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/sectors': typeof SectorsRoute
  '/team': typeof TeamRoute
  '/admin/matches': typeof AdminMatchesRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/waste': typeof AdminWasteRoute
  '/client/matches': typeof ClientMatchesRoute
  '/client/recommendations': typeof ClientRecommendationsRoute
  '/client/scorecard': typeof ClientScorecardRoute
  '/client/waste': typeof ClientWasteRoute
  '/admin/': typeof AdminIndexRoute
  '/client/': typeof ClientIndexRoute
  '/admin/audits/new': typeof AdminAuditsNewRoute
  '/admin/clients/$clientId': typeof AdminClientsClientIdRoute
  '/admin/clients/': typeof AdminClientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/client'
    | '/collaborations'
    | '/contact'
    | '/how-it-works'
    | '/login'
    | '/sectors'
    | '/team'
    | '/admin/matches'
    | '/admin/partners'
    | '/admin/reports'
    | '/admin/users'
    | '/admin/waste'
    | '/client/matches'
    | '/client/recommendations'
    | '/client/scorecard'
    | '/client/waste'
    | '/admin/'
    | '/client/'
    | '/admin/audits/new'
    | '/admin/clients/$clientId'
    | '/admin/clients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collaborations'
    | '/contact'
    | '/how-it-works'
    | '/login'
    | '/sectors'
    | '/team'
    | '/admin/matches'
    | '/admin/partners'
    | '/admin/reports'
    | '/admin/users'
    | '/admin/waste'
    | '/client/matches'
    | '/client/recommendations'
    | '/client/scorecard'
    | '/client/waste'
    | '/admin'
    | '/client'
    | '/admin/audits/new'
    | '/admin/clients/$clientId'
    | '/admin/clients'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/client'
    | '/collaborations'
    | '/contact'
    | '/how-it-works'
    | '/login'
    | '/sectors'
    | '/team'
    | '/admin/matches'
    | '/admin/partners'
    | '/admin/reports'
    | '/admin/users'
    | '/admin/waste'
    | '/client/matches'
    | '/client/recommendations'
    | '/client/scorecard'
    | '/client/waste'
    | '/admin/'
    | '/client/'
    | '/admin/audits/new'
    | '/admin/clients/$clientId'
    | '/admin/clients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ClientRoute: typeof ClientRouteWithChildren
  CollaborationsRoute: typeof CollaborationsRoute
  ContactRoute: typeof ContactRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  SectorsRoute: typeof SectorsRoute
  TeamRoute: typeof TeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collaborations': {
      id: '/collaborations'
      path: '/collaborations'
      fullPath: '/collaborations'
      preLoaderRoute: typeof CollaborationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sectors': {
      id: '/sectors'
      path: '/sectors'
      fullPath: '/sectors'
      preLoaderRoute: typeof SectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/matches': {
      id: '/admin/matches'
      path: '/matches'
      fullPath: '/admin/matches'
      preLoaderRoute: typeof AdminMatchesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/partners': {
      id: '/admin/partners'
      path: '/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AdminPartnersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/waste': {
      id: '/admin/waste'
      path: '/waste'
      fullPath: '/admin/waste'
      preLoaderRoute: typeof AdminWasteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/client/': {
      id: '/client/'
      path: '/'
      fullPath: '/client/'
      preLoaderRoute: typeof ClientIndexRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/matches': {
      id: '/client/matches'
      path: '/matches'
      fullPath: '/client/matches'
      preLoaderRoute: typeof ClientMatchesRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/recommendations': {
      id: '/client/recommendations'
      path: '/recommendations'
      fullPath: '/client/recommendations'
      preLoaderRoute: typeof ClientRecommendationsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/scorecard': {
      id: '/client/scorecard'
      path: '/scorecard'
      fullPath: '/client/scorecard'
      preLoaderRoute: typeof ClientScorecardRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/waste': {
      id: '/client/waste'
      path: '/waste'
      fullPath: '/client/waste'
      preLoaderRoute: typeof ClientWasteRouteImport
      parentRoute: typeof ClientRoute
    }
    '/admin/audits/new': {
      id: '/admin/audits/new'
      path: '/audits/new'
      fullPath: '/admin/audits/new'
      preLoaderRoute: typeof AdminAuditsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients/': {
      id: '/admin/clients/'
      path: '/clients'
      fullPath: '/admin/clients/'
      preLoaderRoute: typeof AdminClientsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients/$clientId': {
      id: '/admin/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/admin/clients/$clientId'
      preLoaderRoute: typeof AdminClientsClientIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminMatchesRoute: typeof AdminMatchesRoute
  AdminPartnersRoute: typeof AdminPartnersRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWasteRoute: typeof AdminWasteRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAuditsNewRoute: typeof AdminAuditsNewRoute
  AdminClientsClientIdRoute: typeof AdminClientsClientIdRoute
  AdminClientsIndexRoute: typeof AdminClientsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminMatchesRoute: AdminMatchesRoute,
  AdminPartnersRoute: AdminPartnersRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWasteRoute: AdminWasteRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAuditsNewRoute: AdminAuditsNewRoute,
  AdminClientsClientIdRoute: AdminClientsClientIdRoute,
  AdminClientsIndexRoute: AdminClientsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ClientRouteChildren {
  ClientMatchesRoute: typeof ClientMatchesRoute
  ClientRecommendationsRoute: typeof ClientRecommendationsRoute
  ClientScorecardRoute: typeof ClientScorecardRoute
  ClientWasteRoute: typeof ClientWasteRoute
  ClientIndexRoute: typeof ClientIndexRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientMatchesRoute: ClientMatchesRoute,
  ClientRecommendationsRoute: ClientRecommendationsRoute,
  ClientScorecardRoute: ClientScorecardRoute,
  ClientWasteRoute: ClientWasteRoute,
  ClientIndexRoute: ClientIndexRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ClientRoute: ClientRouteWithChildren,
  CollaborationsRoute: CollaborationsRoute,
  ContactRoute: ContactRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  SectorsRoute: SectorsRoute,
  TeamRoute: TeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
